### ISSUE TITLE
Error. The size of two sequences is not equal.

### ISSUE THREAD

**Issue by karthickbrlab** [kullrich/kakscalculator2#2] opened 2024-03-29 10:56 UTC
Although both sequences are of same length, it shows,

Error. The size of two sequences in 'D0001' is not equal.

While it is working in example file. So did i make something wrong at generating the input file?

**Comment by kullrich** [comment] 2024-03-29 10:57
Hi, can you send me the fasta file to check. Thx

**Comment by karthickbrlab** [comment] 2024-03-29 11:02
[kaksatp.txt](https://github.com/kullrich/kakscalculator2/files/14803169/kaksatp.txt)

Kindly see this one.

**Comment by kullrich** [comment] 2024-03-29 11:13
The problem is that the sequence length of the coding sequences are not multiple of 3:

I am using the R package `MSA2dis` which has ported the complete KaKs_Calculator models via `Rcpp`

```
> cds<-Biostrings::readDNAStringSet("kaksatp.txt")
> cds
DNAStringSet object of length 2:
    width seq                                               names               
[1]  1523 TATAATTTCTCCTGAAGTAGAAA...TCATCGGCTTTAATGGTTACCAT atpa1
[2]  1523 TATAATTTCTCCTGAAGTAGAAA...TCATCGGCTCTAATGGTTACCAT atpa2
> MSA2dist::dnastring2kaks(cds)
In seqinr::kaks(dnastring2aln(cds)) :
  sequence lengths are not a multiple of 3
```

However, you can use the function `cds2aa(..., return.cds=TRUE)` to shorten the sequences and calculate KaKs as follows:

```
> cds |> MSA2dist::cds2aa(shorten=TRUE, return.cds=TRUE)
DNAStringSet object of length 2:
    width seq                                               names               
[1]  1521 TATAATTTCTCCTGAAGTAGAAA...TTTCATCGGCTTTAATGGTTACC atpa1
[2]  1521 TATAATTTCTCCTGAAGTAGAAA...TTTCATCGGCTCTAATGGTTACC atpa2
```

```
> cds |> MSA2dist::cds2aa(shorten=TRUE, return.cds=TRUE) |> MSA2dist::dnastring2kaks(model="YN")
            Comp1 Comp2  seq1  seq2 Method          Ka        Ks     Ka/Ks
atpa1_atpa2     1     2 atpa1 atpa2     YN 0.000928984 0.0198114 0.0468915
            P-Value(Fisher) Length S-Sites N-Sites Fold-Sites(0:2:4)
atpa1_atpa2     0.000355745   1437   359.8  1077.2                NA
            Substitutions S-Substitutions N-Substitutions
atpa1_atpa2             8               7               1
            Fold-S-Substitutions(0:2:4) Fold-N-Substitutions(0:2:4)
atpa1_atpa2                          NA                          NA
            Divergence-Time
atpa1_atpa2      0.00565681
            Substitution-Rate-Ratio(rTC:rAG:rTA:rCG:rTG:rCA/rCA)
atpa1_atpa2                                          2:2:1:1:1:1
                                       GC(1:2:3) ML-Score AICc Akaike-Weight
atpa1_atpa2 0.400723(0.397436:0.543393:0.261341)       NA   NA            NA
            Model
atpa1_atpa2    NA
```

**Comment by karthickbrlab** [comment] 2024-03-29 11:16
Thank you for your quick reply.

Can i run multiple pairs of sequences at a go?

**Comment by kullrich** [comment] 2024-03-29 11:20
Yes, it is fully parallelised and one can either just calculate all pairwise comparison with the `dnastring2kaks()` function or even use indices with the `indices2kaks()` function. This feature will be in the new bioc-release, but you can install just from github and will have the functionality.
Also to note is that the sequence pairs do not need to be pre-aligned, if one sets the `isMSA=FALSE` parameter the pair will be converted into AA, aligned and back-translated into a codon-alignment which will be used for KaKs calculation.

**Comment by karthickbrlab** [comment] 2024-03-29 11:21
Great one. Thanks a lots

I'm working on a chloroplast genome. After annotation I generated .pep files using gffread and EMBOSS transeq.
I found lot of * in peptide file. Does this mean the conversion is not effective or really they have lot of termination codons?

Kindly let me know the best practice to generate AA or peptide file from annotations.

For example.
>cds-blatx_cds1
.MFYHVPSIH..KKGYMRYLV.K.ANISIGK.GGSKSMRKSLLLLGL.LLSY.VPQL.RFAIHKPFQLAA
KTSLNLSLNSFEM.VKPRLEKNTVHGFPLLEPCFYLFLFLTGQEPFYRGKLSSYLKGS.QHQRMI.IRRL
L.LYSHQ.HIFMRVLAKKD.GISVNTFNQLQFFYPLTS.KILQNPYR.VFDFSEIY.PMN..LLFLFL.Y
L.WFLYLSCSLDYLQAGFKLSFLPL.LRLI.VNLWRVII

**Comment by kullrich** [comment] 2024-03-29 11:22
Just one example would be:

```
> library(MSA2dist)
> ?dnastring2kaks
> data("hiv", package="MSA2dist")
> hiv
DNAStringSet object of length 13:
     width seq                                              names               
 [1]   273 GTAGTAATTAGATCTGAAAACTT...AACAATAGTTTTTAATCAATCC U68496
 [2]   273 ATAGTAATTAGATCTGAAAACTT...AACAATAATCTTTAATCAATCC U68497
 [3]   273 GTAGTAATTAGATCTGAAAACTT...AACAATAGTCTTTAATCAATCC U68498
 [4]   273 ATAGTAATTAGATCTGAAAACTT...AACAATAGTCTTTAATCAATCC U68499
 [5]   273 ATAGTAATTAGATCTGAAAACTT...AACAATAGTCTTTAATCAATCC U68500
 ...   ... ...
 [9]   273 ATAGTAATTAGATCTGAAAACTT...AACAATAGTTTTTAATCAATCC U68504
[10]   273 ATAGTAATTAGATCTGAAAACTT...AACAATAGTCTTTAATCAATCC U68505
[11]   273 ATAGTAATTAGATCTGAAAACTT...AACAATAGTTTTTAATCAATCC U68506
[12]   273 GTAGTAATTCGATCTGAAAACTT...AACAATAGTCTTTAATCAATCC U68507
[13]   273 ATAGTAATCAGATCTGAAAACTT...AACAATAATCTTTAATAATTCC U68508
> head(hiv |> dnastring2kaks(model="YN", threads=2))
              Comp1 Comp2   seq1   seq2 Method        Ka        Ks    Ka/Ks
U68496_U68497     1     2 U68496 U68497     YN 0.0259337 0.0848079 0.305794
U68496_U68498     1     3 U68496 U68498     YN 0.0833439 0.0402529  2.07051
U68496_U68499     1     4 U68496 U68499     YN 0.0888328 0.0375284  2.36709
U68496_U68500     1     5 U68496 U68500     YN   0.11672  0.074978  1.55673
U68496_U68501     1     6 U68496 U68501     YN  0.108488 0.0673923  1.60979
U68496_U68502     1     7 U68496 U68502     YN  0.153774  0.135014  1.13894
```

**Comment by kullrich** [comment] 2024-03-29 11:47
Of course this might be related to the mito-assembly or you need to use a differnet genetic code.

MSA2dist can handle different genetic codes.

see e.g. the `woodmouse` data from the `ape` R package:

```
Cytochrome b Gene Sequences of Woodmice

Description:

     This is a set of 15 sequences of the mitochondrial gene cytochrome
     _b_ of the woodmouse (_Apodemus sylvaticus_) which is a subset of
     the data analysed by Michaux et al. (2003). The full data set is
     available through GenBank (accession numbers AJ511877 to
     AJ511987).
```
```
Biostrings::alphabetFrequency((woodmouse |> dnabin2dnastring() |> cds2aa(shorten=TRUE))[1])
      A R  N  D C Q E  G  H  I  L K M  F  P  S  T W  Y  V U O B J Z X * - + .
[1,] 20 8 12 10 3 4 4 21 12 41 46 8 2 26 19 21 22 0 13 17 0 0 0 0 0 3 9 0 0 0
```

versus, using mito-genetic-code, 9 vs. zero stop codons:

```
Biostrings::alphabetFrequency((woodmouse |> dnabin2dnastring() |> cds2aa(shorten=TRUE, genetic.code=Biostrings::getGeneticCode("2")))[1])
      A R  N  D C Q E  G  H  I  L K  M  F  P  S  T W  Y  V U O B J Z X * - + .
[1,] 20 8 12 10 3 4 4 21 12 28 46 8 15 26 19 21 22 9 13 17 0 0 0 0 0 3 0 0 0 0
```

**Comment by kullrich** [comment] 2024-03-29 11:50
So my suggestion would be to start of with `CDS`, check if the frame is OK and use it with `MSA2dist` for `KaKs` calculation and the corresponding genetic code: https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi

**Comment by kullrich** [comment] 2024-03-29 11:52
Also using the shortened version of your file now works fine with `KaKs_Calculator`

```
KaKs_Calculator -i kaksatp_shorten.txt -o kaksatp_shorten.out -m YN
```

[kaksatp_shorten.txt](https://github.com/kullrich/kakscalculator2/files/14803814/kaksatp_shorten.txt)

Best regards

Kristian

**Closed as completed by kullrich** 2024-03-29 11:52 UTC

**Comment by karthickbrlab** [comment] 2024-03-29 11:59
Thank you very much

It's a lot of help from your side.

**Comment by karthickbrlab** [comment] 2024-03-30 09:56
Hi

How did you shorten that?
